name: A workflow to create a jekyll post from github issue
on:
  issue_comment:
    types: [created, deleted]
jobs:
  build:
    name: A job to create a jekyll post from github issue
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'publish'
    steps:
      - name: Checkout master branch
        uses: actions/checkout@master

      - name: Create jekyll post file
        if: success() && github.event.issue.user.login == 'giovannisciortino'
        run: |
          cat << 'EOF' > $POST_DIRECTORY/${{ github.event.issue.title }}
          ${{ github.event.issue.body }}
          EOF
        env:
          GITHUB_ACCOUNT_JEKYLL_OWNER: 'giovannisciortino'
          POST_DIRECTORY: '_posts'

      - name: Commit files
        if: success()
        run: |
          git config --local user.name '$GIT_USER_NAME'
          git config --local user.email '$GIT_USER_EMAIL'
          git add --all
          git commit -m "$DEFAULT_COMMIT_MESSAGE" -a
        env:
          GIT_USER_NAME: 'Giovanni Sciortino'
          GIT_USER_EMAIL: 'giovannisciortino@gmail.com'
          DEFAULT_COMMIT_MESSAGE: 'New jekyll post create from github issue'
      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
